### PR TITLE
PR: Bugfix when the matrix had no annotation rows

### PR DESCRIPTION
**Pull request by jspaezp**
Hello Jan !

I am submitting a couple of things.

1. Fixed bug that caused the reader to crash when the matrix had no annotation rows.
2. Added an example matrix as a test case.
3. Lightly modified the IO test, for it to be more readable and its output to be more informative when tests fail.
4. Also did some minor modification on the roxygen documentation to reduce redundancy and improve readability.

Let me know if you have any insights.
Best,
Sebastian

### CODE REVIEW

**Comment by jdrudolph** [comment]
Hi Sebastian!

thanks a lot for the bugfix! I think this is almost ready to merge.
 - Could you add a minimal test case for the bug? Our test suite did not cover it until now :-/
 - Please shortly summarize the changes affecting users in `NEWS.md`.

Cheers,
Jan

**Comment by jdrudolph** [comment]
Hi Sebastian!

I somehow looked only  at the first commit and saw that you already added a test case ✔️.

Two more comments regarding the vigniettes and my recent experiences with CRAN compliance:
 - Test and documentation should only write the the temporary directory, not to user folders. (see 73d89b4)
 - We do not need the `.html` version of the vignette checked into the code repository.

Best, Jan

**Comment by jspaezp** [comment]
Hi Jan !

* To the best of my knowledge I did not modify the tests that write to disk so we should be good on that side (and that explains why you changed the tests to use `tempfile`)
* I removed the .html and .R versions of the vignettes and added `vignettes/*.html` and `vignettes/*.R` to the `.gitignore`

On the other hand.

* Whenever writing in the `news.md` ... any conventions you want to keep? (regarding sectioning, numbering and such ...)
* I noticed that not having that test case might have been because Perseus by default generates annotation columns when creating a random matrix (feature request for Perseus ?).

ps: I've noticed you have been in a roll publishing papers as well so congrats on that. Your MQSS class was super cool as well.

Best, 
Sebastian

**Comment by jdrudolph** [comment]
Hi Sebastian,
I just merged your pull request in 6bbcbd6 after making some local changes with so that `devtools::check()` passes without warnings.
 * `NEWS.md` should contain only news for users, e.g. concerning bugs, features, documentation
 * You can always remove the annotation columns in Perseus so I wouldn't bother implementing the changes

Thanks for the praise on the papers etc. but especially for contributing!

**Pull request closed without merging**
