### PR TITLE
Added Functions to integrate with bioconductor

### PR DESCRIPTION
**Pull request by jspaezp**
Hey ! 

I added a couple of functions that add coerce matrixData objects from/to ExpressionSet objects.
Let me know what you think

ps: I am open to suggestion regarding the nomenclature of the functions or pretty much anything else

### CODE REVIEW

**Comment by jdrudolph** [comment]
this is awesome, since it would enable everyone to tap into all the tools available in bioconductor. Maybe we could remove the `matrixData` class entirely so there is a consistent data representation? I implemented the `matrixData` only due to lack of experience with bioconductor...

**Comment by jspaezp** [comment]
It could be done fairly painlessly as i mentioned via e-mail, and we could compensate it by having the parser return a named list (for non-bioconductor dependent-usage) initially and then just having a function that bundles everything into an ExpressionSet object for everything else (it would also make the package a lot lighter because it would not require the installation of all the bioconductor base dependencies).

In addition I was able to note that currently it only supports reading the 'single matrix' representation (without the is.imputed values and the other I one don't remember right now ), I guess it is because the plugin only exports it in that way (currently... I hope), but I guess adding it would not really be that hard and could empower some sections of the workflow analysis (and could allow the imputations done in the R environment to be exported back to perseus in a consistent manner).

Let me know your opinion and I could gladly help implementing some of the wanted changes.
ps: sorry for the ridiculous amount of commits debugging the travis-ci framework, it took me a little more than expected to have successful builds in the platform.

**Comment by jdrudolph** [comment]
is this ready to merge? would you mind adding a small example to the README or the documentation, showing how to use `PerseusR` with `bioconductor`?

**Comment by jspaezp** [comment]
Will do ASAP (sorry for the delay, I have been slightly busier than usual the last couple of weeks) In addition I have been working a little bit on the devel branch of my fork to add support for lists and matrices, along with decent cohersion between those formats. I still need to add a vignette showing the usage of these functions and add a couple or 'try' statements to make them more 'fail-proof'.

Best!, 
Sebastian

**Comment by jdrudolph** [comment]
sounds awesome!

**Comment by jspaezp** [comment]
I believe it is done ... I just realized the readme should be updated (although the vignette explains fairly decently the alternatives ...)

**Comment by jdrudolph** [comment]
thanks so much for your contribution! I hope many people will find this useful.

**Pull request merged**
